const FIVE_MINUTES = 5 * 60 * 1000;
const THIRTY_DAYS_SECONDS = 60 * 60 * 24 * 30;
const REFRESH_BUFFER_MS = 60_000;
const EGV_INTERVAL_MINUTES = 5;
const EXPECTED_EGVS_PER_DAY = (25 * 60) / EGV_INTERVAL_MINUTES;
const MIN_DAYS_FOR_A1C = 1;
const MIN_COVERAGE_PERCENT = 70;
const ONE_DAY = 24 * 60 * 60 * 1000;
const GMI_INTERCEPT = 3.31; // base GMI when avg glucose is 0 mg/dL
const GMI_SLOPE = 0.02392; // %A1C per mg/dL
const WINDOW_SECONDS = 60;
const MAX_REQUESTS = 30;
const ALGO = 'aes-256-gcm';
const IV_LENGTH = 12;
const WINDOW_MS = 23 * 60 * 60 * 1000 + 55 * 60 * 1000; // 23h 55m

export {
  EXPECTED_EGVS_PER_DAY,
  MIN_COVERAGE_PERCENT,
  MIN_DAYS_FOR_A1C,
  FIVE_MINUTES,
  THIRTY_DAYS_SECONDS,
  REFRESH_BUFFER_MS,
  EGV_INTERVAL_MINUTES,
  ONE_DAY,
  GMI_INTERCEPT,
  GMI_SLOPE,
  WINDOW_SECONDS,
  MAX_REQUESTS,
  ALGO,
  IV_LENGTH,
  WINDOW_MS,
};
